version: '3'
services:
  villain:
    build: villain/
    environment:
      - PORT=3000
      - HERO_URL=http://hero:3000/
    ports:
      - "3010:3000"

  hero:
    build: hero/
    environment:
    - PORT=3000
    - VILLAIN_URL=http://villain:3000/
    ports:
    - "3020:3000"

  test:
      build: sls-test/
      environment:
      - PORT=3000
      - HERO_URL=http://hero:3000/
      - VILLAIN_URL=http://villain:3000/
      ports:
      - "3030:3000"

networks:
  poneys: