version: '3'
services:
  sls:
    build: ./sls
    environment:
    - PORT=3000
    ports:
    - "3050:3000"

  api:
    build: ./db
    depends_on:
    - db
    environment:
    - DB=mongodb://db:27017/db
    ports:
    - "3010:3010"

  confederation:
    build: ./confederation
    environment:
    - PORT=3000
    ports:
    - "3020:3020"

  db:
    image: mongo
    ports:
    - "27027:27017"
