version: '3'
services:
  server_villain:
    build: villain
    environment:
      - PORT=8080
      - BASE_URL=http://127.0.0.1:8080/api
      - SUFFIX_URL={ownerId}/relationships/{path}
    ports:
      - "1337:8080"

  server_hero:
      build: hero
      environment:
        - PORT=8081
        - BASE_URL=http://127.0.0.1:8081/api
        - SUFFIX_URL={ownerId}/relationships/{path}
      ports:
        - "1338:8081"