version: '3'
services:
  sls-villain:
    build: ./sls-villain
    ports:
    - "3060:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3060
    - API_CONFEDERATION=http://confederation:3020
    networks:
    - tpsuperheroes

  sls-hero:
    build: ./sls-hero
    ports:
    - "3070:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3060
    - API_CONFEDERATION=http://confederation:3020
    networks:
    - tpsuperheroes

  sls-mount:
    build: ./sls-mount
    ports:
      - "3080:3000"
    links:
      - db
    environment:
      - DB=mongodb://db:27017/db
      - PORT=3060
      - API_CONFEDERATION=http://confederation:3020
    networks:
      - tpsuperheroes

  confederation:
    build: ./confederation
    ports:
    - "3020:3020"
    environment:
    - PORT=3020
    - API_SLS=http://sls:3000
    networks:
    - tpsuperheroes

  db:
    image: mongo
    ports:
    - "27027:27017"
    networks:
      - tpsuperheroes

networks:
  tpsuperheroes:
