version: '3'
services:
  sls:
    build: ./sls
    ports:
    - "3050:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3050
    - API_DB=http://api:3010
    - API_CONFEDERATION=http://confederation:3020
    networks:
    - tpsuperheroes

  manage-db:
    build: ./db
    ports:
    - "3010:3010"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3010
    - API_CONFEDERATION=http://confederation:3020
    - API_SLS=http://sls:3000
    networks:
    - tpsuperheroes

  confederation:
    build: ./confederation
    ports:
    - "3020:3020"
    environment:
    - PORT=3020
    - API_DB=http://api:3010
    - API_SLS=http://sls:3000
    networks:
    - tpsuperheroes

  db:
    image: mongo
    ports:
    - "27027:27017"
    networks:
      - tpsuperheroes

networks:
  tpsuperheroes:
