version: '3'
services:
  test:
    build: sls/
    environment:
    - PORT=3000
    - HERO_URL=http://hero:3000/
    - VILLAIN_URL=http://villain:3000/
    ports:
    - "3050:3000"

  api:
    build: db
    depends_on:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=8080
    ports:
    - "1337:8080"

  db:
    image: mongo
    ports:
    - "27027:27017"
